server:
  port: 8085
base-url:
  context: /adl/et/telco/api/v1.0/user-management-service
app:
  host: localhost:${server.port}

log:
  identifierKey: UUID
  isDebug: true
info:
  app:
    name: sc-core-services
    msName: user-management

com:
  adl:
    dte:
      plugins:
        logging:
          enabled: true
          level: DEBUG
        rolling:
          policy: time
          fileType: .zip
        alarming:
          enabled: true
        msstat:
          enabled: true
spring.zipkin.base-url: http://core-services-zipkin-service.core-services.svc.cluster.local:8085/

#spring.datasource.url : jdbc:mysql://localhost:3306/sc_usermanagement?createDatabaseIfNotExist=true&useUnicode=yes&characterEncoding=UTF-8
#spring.datasource.username : root
#spring.datasource.password : root

spring.datasource.url: jdbc:mysql://192.168.10.10:3306/sc_usermanagement?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=Asia/Colombo&zeroDateTimeBehavior=convertToNull
spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}
spring.datasource.username: ${SPRING_DATASOURCE_USERNAME}

spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.show-sql: false
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

password:
  expiration-period: "P3M"

security.jwt.sign.key: nNQGuZE7S0LUrTWmf4hrfC6epQy6+Z8F7g3Ox/LgAHg=
security.jwt.expiretime.forgot.password.token.millisecond: 900000 #15mins

send.email.url: http://localhost:8098/adl/et/telco/api/v1.0/email-service/send/email

#restconfig
rest.read-timeout: 12000
rest.connect-timeout: 5000

forgot.password.reset.link.url: https://qa-aee.mascom.bw/selfcare-ent-fe-enterprise-sc-fe/reset-password?token=

forgot.password.session.token.expiry.time.in.minutes: 5
maximum.number.of.password.history.records: 5
forgot.password.email.subject: "Set Your New Password"
forgot.password.success.email.subject: "Password Recovered Successfully"
forgot.password.email.from.name: "MASCOM"

security:
  max-login-attempts: 5
  lock-duration-hours: 1

argon2:
  hash-iterations: 3
  memory: 65536
  parallelism: 2

validation:
  regex:
    msisdn: ^(71[0-9]{6}|74(0[0-2][0-9]{5}|5[0-7][0-9]{5})|75(4[0-6][0-9]{5}|9[0-9]{6})|76(0[0-2][0-9]{5}|6[0-7][0-9]{5})|77(0[0-1][0-9]{5}|6[0-7][0-9]{5}|8[0-8][0-9]{5})|79250(000|900|999))$
    email: ^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$

date.time.pattern: yyyy-MM-dd HH:mm:ss

# Database Auditing
hibernate.envers.audit_table_suffix: _AUD
hibernate.envers.revision_field_name: REV
hibernate.envers.revision_type_field_name: REVTYPE
hibernate.envers.store_data_at_delete: true

#Configuration Manager URLs
url.config.createActivity: http://localhost:8084/adl/et/telco/api/v1.0/configuration-manager-service/activity/create
url.for.get.application.configurations: http://localhost:8083/adl/et/telco/api/v1.0/configuration-manager-service/application/config/list